//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ДЭ1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public decimal id { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public string first_name { get; set; }
    }
}
