//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ДЭ1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public decimal id { get; set; }
        public decimal year { get; set; }
        public string litera { get; set; }
        public decimal sub_group { get; set; }
        public decimal count_classes { get; set; }
        public string name { get; set; }
    }
}
